// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackBackend.Models;

#nullable disable

namespace TrackBackend.Migrations
{
    [DbContext(typeof(TrackContext))]
    [Migration("20230701083917_migration_1")]
    partial class migration_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("TrackBackend.Models.OrderSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CtfUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalHeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalWidth")
                        .HasColumnType("TEXT");

                    b.Property<string>("PixelHeight")
                        .HasColumnType("TEXT");

                    b.Property<string>("PixelWidth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("orderSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
